package com.activenetwork.qa.awo.testcases.regression.basic.orms.report.ondemand.excel.resource;

import com.activenetwork.qa.awo.testcases.abstractcases.ResourceManagerTestCase;
import com.activenetwork.qa.awo.util.AwoUtil;
import com.activenetwork.qa.testapi.util.DateFunctions;

/**
 * @Description: this script used to compare report with template, depends on invoice number generated by setup script GenerateTmplate for NRRS invoice report
 * @precondition: this script should be run after setup script generate template
 * @SPEC:TC:037383
 * @Task#:AUTO-1138
 * @author ssong
 * @Date Aug 09, 2012
 */
public class NrrsInvoiceDetailReport_TicketDeliveryMethod extends ResourceManagerTestCase{

	@Override
	public void execute() {
		rm.loginResourceManager(login);
		
		rm.selectOneRpt(rd.group, rd.reportName);
		rm.runSpecialRpt(rd, comparedPath);
		boolean result = rm.verifyEmailReport(templatesPath, rm.getReportFromMailBox(host, username, password, comparedPath,rd.fileName, rd.emailSubject));
		rm.verifyReportCorrect(result);
		
		rm.logoutResourceManager();
	}

	@Override
	public void wrapParameters(Object[] param) {
		login.url = AwoUtil.getOrmsURL(env);
		login.contract = "NRRS Contract";
		login.location = "Administrator/NRRS";

		rd.group = "Financial Reports";
		rd.reportName = "NRRS Invoice Detail Report";
		rd.emailSubject = rd.reportName+DateFunctions.getCurrentTime();
		rd.reportFormat = "XLS";
		rd.deliveryMethod = "EMAIL";
		rd.invoice = rm.readQADB("NRRSInvoice_Ticket");
		rd.fileName =  rd.reportName.replaceAll(" ", "")+"_TicketDeliveryMethod";// can not change, must be consistent with generate template script
	}

}
