--http://wiki.reserveamerica.com/display/dev/Minimum+to+Confirm+Setup

/*--configure table D_TICKET_DELIVERY_METHOD_CFG:
DELIVERY_METHOD_ID
	1:"Mail Out";
	2:"Print at Home";
	3:"Will Call";
TICKET_CATEGORY_ID is 0:"All";
SALE_CHANNEL_ID is 1:"All";
TRANSACTION_OCCURRENCE_ID is NULL:"All";
--*/

alter session set current_schema=live_NRRS;
--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72777,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72777,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72777,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),77813,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),77813,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),77813,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72397,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72397,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72397,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72270,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72270,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72270,3,0,1,null);
commit;

--delete all delivery methods of park 72291
DELETE FROM D_TICKET_DELIVERY_METHOD_CFG  Where LOC_ID = 72291;
commit;
--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72291,3,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72291,2,1,2,38);
commit;


--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72168,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72168,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72168,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72413,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72413,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72413,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72411,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72411,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),72411,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),77813,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),77813,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),77813,3,0,1,null);
commit;

--to setup 'Delivery Method' displayed in Confirmation Letter
--http://spira.qa.reserveamerica.com/SpiraTeam/5/TestCase/38320.aspx
insert into D_LOC_ATTR_VALUE(ID, LOC_ID, ATTR_ID, VALUE) values(get_sequence('D_LOC_ATTR_VALUE'), 72777, 4124, 'yes');
commit;

--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),79052,2,0,1,null);
commit;


--clean up deliver method for 'MAMMOTH CAVE NATIONAL PARK TOURS',due to case 'OrderLevelTranFeeLabel'
delete from D_TICKET_DELIVERY_METHOD_CFG where loc_id=77817;
commit;

alter session set current_schema=live_CA;
--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120101,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120101,2,0,1,null);
commit;

--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120101,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120102,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120102,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120102,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120272,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120272,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120272,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120274,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120274,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120274,3,0,1,null);
commit;

--Mail out
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120265,1,0,1,null);
commit;
--Print at Home
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120265,2,0,1,null);
commit;
--Will Call
insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
values (GET_SEQUENCE('D_TICKET_DELIVERY_METHOD_CFG'),120265,3,0,1,null);
commit;

alter session set current_schema=live_NRRS;
 --Mail Out: 
 insert into  D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
 values (get_sequence('D_TICKET_DELIVERY_METHOD_CFG'),77814,1,0,4,null); 
 --Print at home: 
 insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
 values (get_sequence('D_TICKET_DELIVERY_METHOD_CFG'),77814,2,0,4,null);
 --Will Call: 
 insert into D_TICKET_DELIVERY_METHOD_CFG (ID, LOC_ID, DELIVERY_METHOD_ID, TICKET_CATEGORY_ID, SALE_CHANNEL_ID, TRANSACTION_OCCURRENCE_ID) 
 values (get_sequence('D_TICKET_DELIVERY_METHOD_CFG'),77814,3,0,4,null);
commit;